[local]
localhost ansible_connection=local

[mongodb]
mongodb-qa.daws88sonline.online

[catalogue]
catalogue-qa.daws88sonline.online

[redis]
redis-qa.daws88sonline.online

[all:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=~/.ssh/movie-hub.pem
MONGODB_HOST=mongodb-qa.daws88sonline.online
CATALOGUE_HOST=catalogue-qa.daws88sonline.online
REDIS_HOST=redis-qa.daws88sonline.online