- name: Configure MySQL
  hosts: mysql
  become: yes

  tasks:
    - name: Install MySQL Server
      ansible.builtin.dnf:
        name: mysql-server
        state: present

    - name: Start and Enable MySQL
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: Check if root password is already configured
      ansible.builtin.command: >
        mysql -uroot -pRoboShop@1 -e "SELECT 1;"
      register: mysql_root_check
      ignore_errors: true
      changed_when: false

    - name: Set root password
      ansible.builtin.command:
        cmd: mysql_secure_installation --set-root-pass RoboShop@1
      when: mysql_root_check.rc != 0