- name: Configure RabbitMQ server
  hosts: rabbitmq
  become: yes

  collections:
    - community.rabbitmq

  tasks:

    - name: Copy RabbitMQ repo
      ansible.builtin.copy:
        src: rabbitmq.repo
        dest: /etc/yum.repos.d/rabbitmq.repo

    - name: Install RabbitMQ server
      ansible.builtin.dnf:
        name: rabbitmq-server
        state: present

    - name: Start RabbitMQ
      ansible.builtin.service:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: Create roboshop user
      community.rabbitmq.rabbitmq_user:
        user: roboshop
        password: RoboShop@1
        permissions:
          - vhost: /
            configure_priv: ".*"
            write_priv: ".*"
            read_priv: ".*"
        state: present