---
- name: Configure Shipping
  hosts: shipping
  become: yes

  tasks:

    - name: Install Maven, MySQL client and pip
      ansible.builtin.dnf:
        name:
          - maven
          - mysql
          - python3-pip
        state: present

    - name: Install Python MySQL libraries
      ansible.builtin.pip:
        name: "{{ item }}"
        executable: pip3.9
      loop:
        - cryptography
        - PyMySQL

    - name: Create application user
      ansible.builtin.user:
        name: movie
        system: true
        home: /app
        shell: /sbin/nologin
        comment: "Created movie user"

    - name: Remove old app directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create app directory
      ansible.builtin.file:
        path: /app
        state: directory
        owner: movie
        group: movie
        mode: '0755'

    - name: Remove old shipping zip
      ansible.builtin.file:
        path: /tmp/shipping.zip
        state: absent

    - name: Download shipping application
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
        dest: /tmp/shipping.zip

    - name: Extract shipping application
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes

    - name: Set ownership of application files
      ansible.builtin.file:
        path: /app
        owner: movie
        group: movie
        recurse: yes

    - name: Build shipping application
      ansible.builtin.command:
        cmd: mvn clean package
        chdir: /app

    - name: Rename shipping jar
      ansible.builtin.command:
        cmd: mv target/shipping-1.0.jar shipping.jar
        chdir: /app

    - name: Copy Shipping service file
      ansible.builtin.template:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service
        owner: root
        group: root
        mode: '0644'

    - name: Copy MySQL repository file
      ansible.builtin.copy:
        src: files/mysql.repo
        dest: /etc/yum.repos.d/mysql.repo
        owner: root
        group: root
        mode: '0644'

    - name: Import Shipping database schema
      community.mysql.mysql_db:
        state: import
        name: all
        login_host: "{{ MYSQL_HOST }}"
        login_user: root
        login_password: movie@1
        target: "{{ item }}"
      loop:
        - /app/db/schema.sql
        - /app/db/app-user.sql
        - /app/db/master-data.sql

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start Shipping service
      ansible.builtin.systemd:
        name: shipping
        state: restarted
        enabled: yes