- name: configure user 
  hosts: user
  become: yes
  tasks: 
  - name: Disable NodeJS module
    ansible.builtin.command: dnf module disable nodejs -y

  - name: Enable NodeJS 20 module
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Install NodeJS
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: install nodejs  
    ansible.builtin.dnf:
      name: nodejs 
      state: present

  - name: create a user
    ansible.builtin.user: 
      name: movie
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Created a movie user"

  - name: delete old directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create a directory
    ansible.builtin.file:
      path: /app
      state: directory
      owner: movie
      group: movie
      mode: '0755'

  - name: delete user zip file
    ansible.builtin.file:
        path: /tmp/user.zip
        state: absent

  - name: Download zip file
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip  
      dest: /tmp/user.zip

  - name: unarchive the zip
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: Change ownership of app
    ansible.builtin.file:
      path: /app
      owner: movie
      group: movie
      recurse: yes

  - name: install dependencies
    community.general.npm:
      path: /app

  - name: Copy user service file
    ansible.builtin.template:
      src: user.service 
      dest: /etc/systemd/system/user.service
      owner: root
      group: root
      mode: '0644'

  - name: daemon reload
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Enable and start user service
    ansible.builtin.systemd:
      name: user
      state: restarted
      enabled: yes